SCREEN_COLOR = "black"
SNAKE_INITIAL_COLOR = "white"
BORDER_COLOR = "white"
TEXT_COLOR = "white"

GROW_UP_BY = 3

SCORE_SIZE = 20

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 800

RIGHT = 0
UP = 90
LEFT = 180
DOWN = 270

LIMIT_TOP = SCREEN_HEIGHT / 2
LIMIT_BOTTOM = -LIMIT_TOP
LIMIT_RIGHT = SCREEN_WIDTH / 2
LIMIT_LEFT = -LIMIT_RIGHT

SLEEP_TIME = .1

BONUS_PROBABILITY = 3
SQUARE_BONUS_VALUE = 3
TRIANGLE_BONUS_VALUE = 5
TURTLE_BONUS_VALUE = 10
SQUARE_BONUS_DURATION = 10
TRIANGLE_BONUS_DURATION = 8
TURTLE_BONUS_DURATION = 6
